config/routes.rb
Moviemart::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/auth/:provider/callback' => 'authentications#create'
  get '/movies/search' => 'movies#search'
  resources :authentications
  resources :reviews
  resources :movies
  get "home/index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  root :to => "home#index", :as => 'home'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :reviews
	has_many :viewers
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
	validates_presence_of :review_text
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :authentications
  has_many :movies, through: :reviews
  has_many :reviews
  has_many :viewers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def apply_omniauth(auth)
    	authentications.build(:provider => auth['provider'], :uid => auth['uid'])
    end

    def password_required?
    	(authentications.empty? || !password.blank?) && super
    end

    def email_required?
      (authentications.empty? || !email.blank?) && super
    end
end

app/models/viewer.rb
class Viewer < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:username, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    auth = request.env["omniauth.auth"]
    authentication = Authentication.find_by(:provider => auth['provider'], :uid => auth['uid'])
    if authentication
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create(:provider => auth['provider'], :uid => auth['uid'])
      redirect_to authentications_path
    else
      user = User.new
      user.apply_omniauth(auth)
      user.username = auth['info']['nickname']
      user.email = auth['info']['email']
      if user.save
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = auth.except('extra')
        redirect_to new_user_registration_path
      end 
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    redirect_to authentications_url, :notice => "Successfully destroyed authentication."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def show
		@movie = Movie.find(params[:id])
	end
	def index
		movie = Movie.find(params[:movie_id])
		if params[:what] == "like"
			movie.like += 1
			if movie.save
				viewer = Viewer.new
				viewer.movie_id = params[:movie_id]
				viewer.user_id = current_user[:id]
				viewer.like = 1
				viewer.save!
			end
		elsif params[:what] == "dislike"
			movie.dislike += 1
			if movie.save
				viewer = Viewer.new
				viewer.movie_id = params[:movie_id]
				viewer.user_id = current_user[:id]
				viewer.like = 0
				viewer.save!
			end
		elsif params[:what] == "nodislike"
			movie.dislike -= 1
			if movie.save
				viewer = Viewer.find_by(:user_id => current_user[:id], :movie_id => params[:movie_id])
				viewer.destroy
			end
		elsif params[:what] == "unlike"
			movie.like -= 1
			if movie.save
				viewer = Viewer.find_by(:user_id => current_user[:id], :movie_id => params[:movie_id])
				viewer.destroy
			end
		elsif params[:what] == "updatedislike"
			movie.like -= 1
			movie.dislike += 1
			if movie.save
				viewer = Viewer.find_by(:user_id => current_user[:id], :movie_id => params[:movie_id])
				viewer.like = 0
				viewer.save
			end
		elsif params[:what] == "updatelike"
			movie.like += 1
			movie.dislike -= 1
			if movie.save
				viewer = Viewer.find_by(:user_id => current_user[:id], :movie_id => params[:movie_id])
				viewer.like = 1
				viewer.save
			end
		end
		redirect_to "/movies/#{params[:movie_id]}"	
	end
	def search
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def create
		super
		session[:omniauth] = nil unless @user.new_record?
	end

	private
	def build_resource(*args)
		super
		if session[:omniauth]
			@user.apply_omniauth(session[:omniauth])
			@user.valid?
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
	def create
		@review = User.find(current_user[:id]).reviews.new(review_params)
		@review.like = 0
  		@review.save
  		redirect_to "/movies/#{params[:review][:movie_id]}"
	end

	private
	  def review_params
	    params.require(:review).permit(:user_id, :review_text, :like, :movie_id)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/authentications/index.html.erb
<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
  </tr>
  <% if @authentications %>
    <% for authentication in @authentications %>
      <tr>
        <td><%= authentication.user_id %></td>
        <td><%= authentication.provider %></td>
        <td><%= authentication.uid %></td>
        <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/home/index.html.erb
<head>
		<title>Movie Revies</title>
		<%= javascript_include_tag "jquery_1_10_2" %>
    	<%= javascript_include_tag "jquery.cycle.all" %>
    	<%= javascript_include_tag "jquery-welcome" %>

    	<style>
			@font-face {
	font-family: 'icomoon';
	src:url('/assets/fonts/icomoon.eot');
	src:url('/assets/fonts/icomoon.eot?#iefix') format('embedded-opentype'),
	url('/assets/fonts/icomoon.woff') format('woff'),
	url('/assets/fonts/icomoon.ttf') format('truetype'),
	url('/assets/fonts/icomoon.svg#icomoon') format('svg');
	font-weight: normal;
	font-style: normal;
}

[class^="icon-"], [class*=" icon-"] {
	font-family: 'icomoon';
	speak: none;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	text-transform: none;
	line-height: 1;

	/* Better Font Rendering =========== */
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
}
.icon-google-plus, .icon-facebook, .icon-twitter, .icon-user{
    font-weight: bold;
    padding-top: 10px;
    padding-left: 15px;
    font-size: 18px
}
.icon-google-plus:before {
	content: "\e600";
}
.icon-facebook:before {
	content: "\e601";
}
.icon-twitter:before {
	content: "\e602";
}
.icon-user:before {
	content: "\e603";
}

.container{
	width: 100%;
	background-image: url("\assets\bing.jpg");
	padding: 0%;
	font-family: "Lato";
}
header{
	width:100%;
	z-index: 100;
	height: 35px;
	background-color:#3a6896;
	position: fixed; 
}
header a{
	margin-top: 7px;
	font-size: 16px;
	vertical-align: top;
	width:22px;
	color: #fff;
}
header span.status{
	margin-top: 7px;
	font-size: 16px;
	vertical-align: top;
	color: #fff;
}
header a:hover{
	text-decoration: none;
}
.mid-container{
	position: fixed;
	opacity: 0.9;
	z-index: 100;
}
.image-hor{
	background-color: #F6EAEA;
	padding: 0px; 
	outline: #FCFAFA solid 0px;
}

.row{
	text-align: center;
	display: inline-block;
	padding: 0px;
	margin: 0px;
}
.col-md-1, .col-md-2{
	
}
.slid-background{
	padding: 0px;
	margin: 0px;
}
.search-bar{
	z-index: 200;
	font-weight: bold;
	display: inline-block;
	top:65%;
	left: 10%;
	width: 60%;
	right: 0%;
	height: 9%;
	font-size: 13px;
	text-align: center;
	opacity: 0.8;
	position: fixed;
	border: 0px;
}
.row{
   margin: 0px;
   padding: 0px;	
}
.search-bar .search-field{
	vertical-align: middle;
	opacity:0.99;
	color: #fff;
	background: #428bca;
	border:4px solid #2a2a2a;
	border-radius: 3px;
	text-align: center;
	font-size: 25px;
	width: 100%;
}
.row ul{
	padding: 0px;
	margin: 0px;
	outline: 0px;
}
.glyphicon-search{
	width: 9%;
	height: 100%;
	padding-left: 10px;
	margin-left: -6px;
	background: #428bca;
	vertical-align: middle;
}
.search-bar .search-field input{
	outline: 0px;
	text-align: left;
	border:0px;
	opacity:0.9;
	height: 47px;
	width: 90%;
	font-style: italic;
	margin-left: -6px;
	background-color: #f8f8f8;
	padding: 5px;	
}
.footer{
	display: inline-block;
	text-align: right;
	z-index: 2;
	background: #3a6896;
	position: fixed;
	bottom: 0%;
	left: 0%;
	right: 0%;
	padding-top: 20px;
	padding-right: 20px;
	height: 10%;
	width: 100%;
	display: inline-block;
}
.img-block-1, .img-block-2,.img-block-3,.img-block-4{
	position:fixed;
	top: 0%;
	bottom:0%;
	width: 25%;
}
.img-block-2{
	left: 25%;
}
.img-block-3{
	left: 50%;
}
.img-block-4{
	left: 75%;
}

.first{
	width: 100%;   
}
.second{
	width:100%;   
}
ul{
	top:35px;
	padding: 0px;
	margin: 0px;
	outline: 0px;
}
li{
	position: fixed;
	top:35px;
	width: 100%;
	padding: 0px;
	margin: 0px;
	width:100%; 
	list-style: none;
}

footer{
	position: fixed;
	background: #3a6896;
	height: 35px;
	width: 100%;
	bottom: 0px;
	z-index: 100;
	text-align: center;
	padding-top: 7px;
}
footer a{
	color: white;
}
a:hover{
	text-decoration: none;
	font-weight: bold;
	color: #fff;
}

    	</style>
	</head>
	<body>
		<div class="container">
			<header class="row" >
			<% if !user_signed_in? %>
				<a href="/auth/gplus" class="col-xs-1"><span class="icon-google-plus"></span>&nbsp&nbspLogin</a>
				<a href="/auth/facebook" class="col-xs-1"><span class="icon-facebook"></span>&nbspLogin</a>
				<a href="#" class="col-xs-1"><span class="icon-twitter"></span>&nbspLogin</a>
				<a href="#" class="col-xs-2"  data-toggle='modal' data-target='#myModal' style="text-align:left;"><span class="icon-user"></span> Login</a>
				<a href="#" class="col-xs-5"></a>
				
				<a href="#" class="col-xs-2" data-toggle='modal' data-target='#registerModal' style="text-align:right;"><span class="icon-user"></span>&nbsp&nbspRegister</a>
				<% else %>
				<a href="#" class="col-xs-1"></a>
				<a href="#" class="col-xs-1"></a>
				<a href="#" class="col-xs-1"></a>
				<a href="#" class="col-xs-2" style="text-align:left;"></a>
				<a href="#" class="col-xs-3"></a>
				
				<span class="col-xs-4 status">Welcome <%= current_user.username || current_user.email %>  |  <%= link_to "Logout", destroy_user_session_path, method: :delete %></span>
			<% end %>
			</header>
			<div class="slid-backgrounds">
				<ul class=" img-block image-hor">
				   <li class="image-hor">
				     <img src="/assets/bing.jpg" class="img-responsive image-hor" />
				   </li>
				   
			    </ul>
			</div>
			<div class="row mid-container">
			<div class="results col-xs-8"></div>
			<div class="todays-review col-xs-4"></div>
			</div>
			<div class="search-bar row">
			    <span class="search-field row">
			   <input type="text" class="" 
			   name="Search Movie" placeholder="Search Movie..." />
			   <span class="glyphicon glyphicon-search">
				</span>
			   </span>
			</div>
			<footer class="nav nav-tabs">
			    <a href="" class="col-xs-10"></a>
			    <a href="#" class="col-xs-1" >About us</a>
				<a href="#" class="col-xs-1" >Feedback</a>
			</footer>
		</div>
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Log In</button>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Register</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>


   <div><%= f.label :username %><br />
  <%= f.text_field :username %></div>


  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Register</button>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
	</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviemart</title>
  <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Exo+2:600' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Chau+Philomene+One' rel='stylesheet' type='text/css'>
</head>
<body>
   
    <!-- 	<% if !user_signed_in? %>
    		
    		<%= link_to "Sign Up", new_user_registration_path %> 

    	<% end %>
  -->

<%= yield %>

</body>
</html>

app/views/movies/_stats.html.erb
<div class="statistics">
			<div class="container">
				<div class="row stats">
					<div class="stat-icon"></div>
					<div class="containts">
						<div class="charts">
							<div class="row stats-box">
							<div class="col-xs-4 ">

								<div class="chart" data-percent="<%= ((((@movie.like).to_f)/(@movie.like+@movie.dislike))*100).round %>" data-col="#24a23e">
									<span>Like: </span><span class="percent"></span>
								</div>
							</div>
							<div class="col-xs-4">
								<div class="chart" data-percent="<%= ((((@movie.dislike).to_f)/(@movie.like+@movie.dislike))*100).round %>" data-col="#eb3d3d">
									<span>Dislike: </span><span class="percent"></span>
								</div>
							</div>
							<div class="col-xs-4">
								<div class="chart" data-percent="<%= @movie.rating %>" data-col="#3a6896">
									<span>Popularity: </span><span class="percent"></span>
								</div>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>  <!-- Statistics -->

app/views/movies/search.html.erb
<head>
	<title>MovieMart</title>
	<%= javascript_include_tag "jquery-pie" %>
	<%= javascript_include_tag "jquery-pie-draw" %>
	<%= javascript_include_tag "easypiechart" %>
	<%= javascript_include_tag "barchart" %>
	<%= javascript_include_tag "jquery-typing" %>
	<%= javascript_include_tag "jqueryanimation" %>
</head>
<body>
<header class="header">
			<div class="container">
				<div class="row">
					<div class="col-xs-4">
						<div class="row">
							<div class="col-xs-3">
								<div class="row">
									<div class="col-xs-2"></div>
									
										<%= link_to raw("<div class='col-xs-10 menu-bar text-center'><span class='glyphicon glyphicon-home home-icon'></span></div>"), home_path %>
									
								</div>
							</div>
							<div class="col-xs-9 logo-text">
								<%= link_to "Moviemart", home_path, :class=>'logo-text' %>
							</div>
						</div>
					</div>
					<div class="col-xs-4 search-bar">
						<div class="input-group">
 							 <input type="text" class="form-control search-input">
  							<span class="input-group-addon search-lens-box"><span class="glyphicon glyphicon-search search-lens"></span></span>
						</div>
					</div> <!-- search bar -->
					<div class="col-xs-4">
						<div class="row">
							<div class="col-xs-9 text-center social">
							<% if user_signed_in? %>
								<%= raw("<span class='fa social-icons username'>#{current_user.username || current_user.email}</span>") %>
							<% else %>
								<%= link_to raw("<span class='fa fa-facebook social-icons'></span>"), "/auth/facebook" %>
								<%= link_to raw("<span class='fa fa-twitter social-icons'></span>"), "#" %>
								<%= link_to raw("<span class='fa fa-google-plus social-icons'></span>"), "/auth/gplus" %>
							<% end %>
							</div> <!-- Social icons -->
							<div class="col-xs-3 user">
							<% if user_signed_in? %>
								<%= link_to raw("<span class='glyphicon glyphicon-log-out social-icons'></span>"), destroy_user_session_path, method: :delete %>
							<% else %>
								<a href="#"><span class='glyphicon glyphicon-log-in social-icons' data-toggle='modal' data-target='#myModal'></span></a>
							<% end %>
							</div>
						</div>
					</div> <!-- User  -->
				</div>
			</div>
		</header> <!-- header -->
		<div class="search-result">
			<div class="container">
				<div class="row">
					<div class="col-xs-4 movie-unit">
						<div class="movie-thumb">
							<img src="/assets/thumb.png">
						</div>
						<div class="movie-title">
							<a href="#"><span>The dark knight</span></a>
						</div>
						<div class="movie-rate">
							<div class="row">
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-up thumb-like"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-like">50%</span>
										</div>
									</div>
								</div>
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-down thumb-dislike"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-dislike">50%</span>
										</div>
									</div>
								</div>
							
							</div>
						</div>
						<a href="#">
							<label class="movie-view">
							 View details <span class="glyphicon glyphicon-chevron-right"></span>
							</label>
						</a>
					</div>
					<div class="col-xs-4 movie-unit">
						<div class="movie-thumb">
							<img src="/assets/thumb.png">
						</div>
						<div class="movie-title">
							<a href="#"><span>The dark knight</span></a>
						</div>
						<div class="movie-rate">
							<div class="row">
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-up thumb-like"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-like">50%</span>
										</div>
									</div>
								</div>
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-down thumb-dislike"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-dislike">50%</span>
										</div>
									</div>
								</div>
								
							</div>
						</div>
						<a href="#">
							<label class="movie-view">
							 View details <span class="glyphicon glyphicon-chevron-right"></span>
							</label>
						</a>
					</div>
					<div class="col-xs-4 movie-unit">
						<div class="movie-thumb">
							<img src="/assets/thumb.png">
						</div>
						<div class="movie-title">
							<a href="#"><span>The dark knight</span></a>
						</div>
						<div class="movie-rate">
							<div class="row">
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-up thumb-like"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-like">50%</span>
										</div>
									</div>
								</div>
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-down thumb-dislike"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-dislike">50%</span>
										</div>
									</div>
								</div>
								
							</div>
						</div>
						<a href="#">
							<label class="movie-view">
							 View details <span class="glyphicon glyphicon-chevron-right"></span>
							</label>
						</a>
					</div>
					<div class="col-xs-4 movie-unit">
						<div class="movie-thumb">
							<img src="/assets/thumb.png">
						</div>
						<div class="movie-title">
							<a href="#"><span>The dark knight</span></a>
						</div>
						<div class="movie-rate">
							<div class="row">
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-up thumb-like"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-like">50%</span>
										</div>
									</div>
								</div>
								<div class="col-xs-4">
									<div class="row">
										<div class="col-xs-6">
											<span class="glyphicon glyphicon-thumbs-down thumb-dislike"></span>
										</div>
										<div class="col-xs-6 clear-left-pad">
											<span class="thumb-dislike">50%</span>
										</div>
									</div>
								</div>
								
							</div>
						</div>
						<a href="#">
							<label class="movie-view">
							 View details <span class="glyphicon glyphicon-chevron-right"></span>
							</label>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bar">
     		<div class="container">
			<div class="row footer">
				<div class="col-md-12 copy-text">
					<span class="copyright">
						<img  src="/assets/copy.png">
						Copyrights 2014 <a href="#">@codingmart.com</a>
					</span>	
					<span class="footer-text">
						<span class="foot-line pull-right">
							<a href="#" class="border-side">Home</a>

							<a href="#" class="border-side">About us</a>

							<a href="#">Contact us</a>

						</span>
					</span>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Log In</button>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</body>

app/views/reviews/_form.html.erb
<% reviews = Review.where(:movie_id => movie_id).order(id: :desc) %>
<% back = ['seagreen-bg', 'purple-bg', 'yellow-bg', 'green-bg', 'blue-bg'] %>

<div class="container">
		<div class="row statis">
			<!-- <div class="col-xs-1"></div> -->
			<div class="col-xs-12 review-check">
				<div class="public-reviews">
				<div class="post-comment">
					<% if user_signed_in? %>
					
					<% end %>
					<% if user_signed_in? %>
					<%= form_for :review, url: reviews_path do |f| %>
					<p>
						<%= f.text_area :review_text, :class=>'text-area' %>
						<%= f.text_field :movie_id, :value => movie_id, :hidden => true %>
					</p>
					<p>
						<button type="submit" class="reply">LEAVE A REVIEW</button>
					</p>
					<% end %>
					<% end %>
				</div>

				<% if reviews.count != 0 %>
				<div class="public-title">Public Reviews</div>
				<% end %>

					<div class="all-reviews">
					<% reviews.each do |r| %>
						<div class="each-review">
							<%=
							raw("<div class='img-holder #{back[rand(4)]}''><img src='/assets/public-reviews-img.png'/></div>")
							%>
							<div class="details">
								<div class="detail-title">
									<span class="name"><% u = User.find(r.user_id) %><%= u.username || u.email %></span>
								</div>
								<div class="msg"><%= r.review_text %></div>
							</div>
						</div>
						<% end %>
					</div>
					
				</div>
			</div>

			<!-- <div class="col-xs-1"></div> -->

		</div>
		</div>